module.exports = {
  userNotFound: 'The user id %s does not exist.',
  notFound: '%s Not Found.',
  userListNotFound: 'Unable to obtain user list.',
  unableToUpdateOtherUser: 'You are unable to update other user.',
  emailDuplicate: 'The email address %s is already in use.',
  userDisabled: 'The user with the email address %s has been disabled.',
  socialDuplicate: 'The %s id is already registered, Try Login.',
  titleDuplicate: 'A project with same title already exists.',
  activeExisting: 'An Active project already exists for this user.',
  projectDoesNotExist: 'A project for this paticular id does not exist.',
  duplicateMember:
    'A team member with same name already exists for this project.',
  teamMemberNotFound: 'A team member with this id does not exist.',
  authError: 'You are not authorized.',
  invalidCredentials: 'Invalid Credentials.',
  infoMissing: 'Missing %s Info.',
  infoUnwanted: 'Unnecessary %s Info.',
  adminDeleteError: 'Cannot delete admin!',
  tokenInvalid: 'Invalid Token.',
  tokenExpired: 'Token Expired.',
  alreadySubmitted: '%s already submitted',
};
