name: Test and Deploy
on:
  push:
    branches: ['master', 'upgrades*']
jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: jumpstarter
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Use Node.js 12.18.1
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.1'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn cache
        uses: actions/cache@v2
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nodemodules-

      - name: Install modules if cache not found
        if: |
          steps.cache-yarn-cache.outputs.cache-hit != 'true' ||
          steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Create .env.test from .example.env
        run: cp .example.env .env.test

      - name: Run database rollback, migration, seeding and tests with coverage
        run: yarn test:coverage

  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deployment steps here
        run: echo "Deployment steps placeholder"
